import { motion } from "framer-motion";
import { Card } from "./ui/card";
import { Badge } from "./ui/badge";
import ScoreGauge from "./ScoreGauge";
import ExplanationPanel from "./ExplanationPanel";
import { CheckCircle, AlertTriangle, XCircle } from "lucide-react";

interface ResultData {
  score: number;
  type: string;
  insights: string[];
}

interface Props {
  result: ResultData;
  onReset: () => void;
}

function getStatus(score: number) {
  if (score < 40) return { label: "Likely Human", icon: CheckCircle, variant: "default" as const, className: "bg-green-500/10 text-green-500 border-green-500/20" };
  if (score < 70) return { label: "Uncertain", icon: AlertTriangle, variant: "default" as const, className: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20" };
  return { label: "Likely AI", icon: XCircle, variant: "default" as const, className: "bg-red-500/10 text-red-500 border-red-500/20" };
}

export default function ResultCard({ result, onReset }: Props) {
  const status = getStatus(result.score);
  const Icon = status.icon;

  return (
    <section id="results" className="py-24 px-6">
      <div className="max-w-3xl mx-auto space-y-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <Card className="glass rounded-2xl p-8 text-center">
            <Badge variant={status.variant} className={`mb-6 text-sm px-4 py-1.5 ${status.className}`}>
              <Icon className="w-4 h-4 mr-1.5" />
              {status.label}
            </Badge>
            <ScoreGauge score={result.score} />
            <p className="mt-6 text-muted-foreground">
              Our analysis indicates a <strong className="text-foreground">{result.score}%</strong> probability this {result.type} content was generated by AI.
            </p>
          </Card>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          <ExplanationPanel insights={result.insights} />
        </motion.div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          className="text-center"
        >
          <button
            onClick={onReset}
            className="text-sm text-muted-foreground hover:text-foreground underline underline-offset-4 transition-colors"
          >
            Analyze another file
          </button>
        </motion.div>
      </div>
    </section>
  );
}
